rem             Ordres concernant DMTSDF
rem
OUVPORTAIL$
Repäre               %3d
Nombre               %2d
DÇsignation          %30s
Matiäre              %11s
Observation          %15s
RÇfÇrence            %11s
rem
rem
rem             Ordres concernant TRTSDF
rem
rem
cle_primaire, Repäre
decroissant
rem
rem
rem             Ordres concernant SDFMTF
rem
rem
hauteur_espace_bas, 1.4844
hauteur_espace_haut, 1.4844
largeur_espace_droit, 1.5822
largeur_espace_gauche, 1.5822
origine, 2
largeur_texte, 2.375
hauteur_texte, 5.0312
police_texte, C:\DMT10\CFG\CONFIG\police6.def
nbre_ligne, 20
